zeebe.client:
  cloud:
    region: XXX-X
    clusterId: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    clientId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    clientSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX